/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.epam.lab;

public class App {
    public static void main(String[] args) {
        System.out.println(Utils.isAllPositiveNumbers("12", "42", "14"));
    }
}
